<?php

namespace App\Admin\Controllers;

use App\Models\OfficerReport;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Show;

class OfficerReportController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'Extension Officers Reports';

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new OfficerReport());

        $grid->column('id', __('Id'));
        $grid->column('created_at', __('Created at'));
        $grid->column('updated_at', __('Updated at'));
        $grid->column('user_id', __('User id'));
        $grid->column('year_id', __('Year id'));
        $grid->column('district_id', __('District id'));
        $grid->column('department_id', __('Department id'));
        $grid->column('generated_by', __('Generated by'));
        $grid->column('total_budget', __('Total budget'));
        $grid->column('comment', __('Comment'));
        $grid->column('submited', __('Submited'));
        $grid->column('print', __('Print'))->display(function () {
            return '<a target="_blank" href="' . url('report-officer-print?id='.$this->id) . '" >PRINT REPORT</a>';
        });

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(OfficerReport::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('created_at', __('Created at'));
        $show->field('updated_at', __('Updated at'));
        $show->field('user_id', __('User id'));
        $show->field('year_id', __('Year id'));
        $show->field('district_id', __('District id'));
        $show->field('department_id', __('Department id'));
        $show->field('generated_by', __('Generated by'));
        $show->field('total_budget', __('Total budget'));
        $show->field('comment', __('Comment'));
        $show->field('submited', __('Submited'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new OfficerReport());

        $form->number('user_id', __('User id'));
        $form->number('year_id', __('Year id'));
        $form->number('district_id', __('District id'));
        $form->number('department_id', __('Department id'));
        $form->number('generated_by', __('Generated by'));
        $form->number('total_budget', __('Total budget'));
        $form->textarea('comment', __('Comment'));
        $form->text('submited', __('Submited'));

        return $form;
    }
}
